Program = StmtList ;

Block = "{" StmtList "}" ;
StmtList = { Stmt ";" } ;

Stmt = IfStmt | WhileStmt | Assignment | Command ;

IfStmt = "if" Command Block [ "else" ( IfStmt | Block ) ] ;

WhileStmt = "while" Command Block ;

Assignment = NameValuePair { NameValuePair } ;

Command = [ Assignment ] CommandName { Argument } ;
CommandName = Word ;
Argument = Word ;

NameValuePair = /* TBD */ ;
Word = /* TBD */ ;
