Program = StmtList ;

Block = "{" StmtList "}" ;
StmtList = { Stmt ";" } ;

Stmt = IfStmt | Command ;

IfStmt = "if" Command Block [ "else" ( IfStmt | Block ) ] ;

Command = CommandName { Argument } ;
CommandName = Word ;
Argument = Word ;

Word = /* TBD */ ;
