Program = StmtList ;

Block = "{" StmtList "}" ;
StmtList = { Stmt ";" } ;

Stmt = IfStmt | WhileStmt | ExportStmt | Assignment | Command ;

IfStmt = "if" Command Block [ "else" ( IfStmt | Block ) ] ;

WhileStmt = "while" Command Block ;

ExportStmt = "export" Exportable { Exportable } ;
Exportable = Name | NameValuePair ;

Assignment = NameValuePair { NameValuePair } ;

Command = [ Assignment ] CommandName { Argument } [ Pipeline ] ;
CommandName = Word ;
Argument = Word ;
Pipeline = "|" Command ;

Word = /* TBD */ ;
Name = /* TBD */ ;
NameValuePair = /* TBD */ ;
